### ISSUE TITLE
cli-go transition?

### ISSUE THREAD

**Issue by sbowman-mitre** [raumfeld/Artifactory.cmake#1]
Hi, thanks for this awesome tool! I suspect it's just what I need to automate a bunch of interdependent CMake builds. I've noticed that JFrog has deprecated the cli tool that you originally built this from. If I use their newer tool ([here](https://github.com/jfrogdev/jfrog-cli-go)) does this tool need to change at all? Or would the change be transparent?

**Comment by ghost** [comment]
Hi! I had a quick look at jfrog-cli and it looks like it works the same way as artifactory-cli. Not sure if the change would be as simple as just using the new jfrog-cli tool, but that's worth a try, and in any case I don't think much work would be needed to support the new tool.

**Comment by sbowman-mitre** [comment]
Okay, that answer suffices for me. I've already forked. I'll try to use the recommended CLI tool and give you a PR if that requires changes.

**Comment by svenfoo** [comment]
I've pushed our change to migrate to jfrog-cli. Sorry for not pushing this earlier...

**Comment by sbowman-mitre** [comment]
awesome! thanks!
